
version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/apollonia
    depends_on:
      - mongo
